# Generated by Django 4.1.1 on 2022-12-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.IntegerField(default=1)),
                ("day_of_week", models.IntegerField(default=1)),
                ("bookmarks", models.ManyToManyField(to="feed.article")),
                ("subscription", models.ManyToManyField(to="feed.journal")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="journal",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
