# Generated by Django 4.1.1 on 2022-12-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_settings_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
